language: java

jdk: openjdk14

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      kirbel74@gmail.com
    on_success: never
    on_failure: always

env:
  global: CODECOV_TOKEN="9aaf5e91-82d4-42ff-be72-2b98581cc822"